import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { stringify } from "yaml";
import { readData } from "./lib/io.mjs";
import { projectCore, prdPath } from "./lib/runtime.mjs";
const root = process.cwd(),
  manifest = readData(root, prdPath + "standard.yaml");
writeFileSync(
  resolve(root, manifest.runtime_contracts.core),
  "# Generated by npm run generate. Edit the declared source owners.\n" +
    stringify(
      projectCore(manifest, readData(root, manifest.validation.semantic_rules)),
      { lineWidth: 110 },
    ),
);
